---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: amazonlinux2
    image: geerlingguy/docker-amazonlinux2-ansible:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
  - name: centos8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks, timer, yaml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
