---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  gather_facts: false
  tasks:
  - name: Check gopass version
    ansible.builtin.command: gopass --version
    register: output
  - name: Assert that gopass is installed
    ansible.builtin.assert:
      that:
      - "'gopass {{ gopass_version }}' in output.stdout"
